baseURL = "http://emmanuelay.se/"
languageCode = "en-us"
title = "Streams of thought"
theme = "aurelius"
disableKinds = ["taxonomy", "term"]
disableHugoGeneratorInject = true
paginate = 1
pygmentsCodeFences = true

[params]
	Author = "Emmanuel Ay"
	description = "Emmanuel Ays personal webpage"
	Keywords = "emmanuel ay, mani, emmanuel mani ay, block21"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    noClasses = true
    style = "dracula"
    tabWidth = 2